apiVersion: v1
kind: Service
metadata:
  name: webapp-tomcat
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8080
    nodePort: 30029
    name: tomcat
  - port: 8082
    targetPort: 8888
    nodePort: 30028
    name: front
  selector:
    app: webapp
